package com.feas.security.config;

public interface PermissionConstants {

    String ANONYMOUS = "anonymous";

    String CREATE_IDEA = "CREATE_IDEA";
    String DELETE_IDEA = "DELETE_IDEA";
    String CREATE_CHALLENGE = "CREATE_CHALLENGE";
    String DELETE_CHALLENGE = "DELETE_CHALLENGE";
    String EDIT_CHALLENGE = "EDIT_CHALLENGE";
    String CREATE_TEAM = "CREATE_TEAM";
    String DELETE_COMMENT = "DELETE_COMMENT";
    String CREATE_ADMIN = "CREATE_ADMIN";
    String REMOVE_ADMIN = "REMOVE_ADMIN";
    String CREATE_JUDGE = "CREATE_JUDGE";
    String REMOVE_JUDGE = "REMOVE_JUDGE";
    String CREATE_LOOKUP = "CREATE_LOOKUP";
    String EDIT_LOOKUP = "EDIT_LOOKUP";
    String DELETE_LOOKUP = "DELETE_LOOKUP";
    String VIEW_EXPERT_REVIEW_PAGE = "VIEW_EXPERT_REVIEW_PAGE";
    String VIEW_SELECTION_COMMITE_PAGE = "VIEW_SELECTION_COMMITE_PAGE";
    String VIEW_WINNING_PODIUM_PAGE = "VIEW_WINNING_PODIUM_PAGE";
    String UPDATE_STAGE = "UPDATE_STAGE";
    String SUPER_ADMIN_EVAL = "SUPER_ADMIN_EVAL";
    String VIEW_QUARTERS="VIEW_QUARTERS";
    String ADMIN_EVAL = "ADMIN_EVAL";

}
